import type { Metadata } from "next";
import { Alexandria } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import ToastNotification from "@/shared/components/ui/toastNotification/ToastNotification";
import { RequestQuoteModal } from "@/shared/components/ui/Modals/RequestQuoteModal/RequestQuoteModal";


const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${alexandria.variable} antialiased`}
      >
        <Providers>
          {children}
          <RequestQuoteModal />
        </Providers>
        <ToastNotification/>
      </body>
    </html>
  );
}
